// <auto-generated />
namespace ControleDeEstoqueUP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Banco1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Banco1));
        
        string IMigrationMetadata.Id
        {
            get { return "201909262011179_Banco1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
