// <auto-generated />
namespace ControleDeEstoqueUP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Banco2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Banco2));
        
        string IMigrationMetadata.Id
        {
            get { return "201909252045427_Banco2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
